Python/Django_Fundamentals/belt_reviewer/apps/review/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^new$', views.new, name='new'),
    url(r'^(?P<id>\d+)$', views.book, name='book'),
]

Python/Django_Fundamentals/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^books/', include('apps.review.urls', namespace='books'))
]

Python/Django_Fundamentals/belt_reviewer/apps/review/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
from ..login.models import User

# Create your models here.
class BookManager(models.Manager):
    def authors(self, author_test,compare):
        if author_test == 'add_my_own':
            author = compare
        else:
            author = author_test
        print author
        return author
    def validator(self,validate):
        if Books.objects.filter(title = validate['title']).exists():
            messages.error(request, 'Book Already Exists')
            return True
        else:
            Books.objects.create(title = validate['title'], author = validate['author'], review = validate['review'], rating = validate['rating'])
            id = Books.objects.only('id').get(title = validate['title']).id
            return id

class Books(models.Model):
    title = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = BookManager()

class Author(models.Model):
    author = models.CharField(max_length=60)
    books = models.ForeignKey(Books, related_name='author')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Reviews(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    books = models.ForeignKey(Books, related_name='reviews')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

Python/Django_Fundamentals/belt_reviewer/apps/review/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import Books

# Create your views here.

def index(request):
    return render(request, 'review/index.html')

def add(request):
    context = {
    'authors': Books.objects.all()
    }
    print context['authors'][0].author
    return render(request, 'review/add.html', context)

def new(request):
    author_test = request.POST['author_select']
    compare = request.POST['author_input']
    author = Books.objects.authors(author_test,compare)
    validate = {
    'title': request.POST['title'],
    'author': author,
    'review': request.POST['review'],
    'rating': request.POST['rating']
    }
    id = Books.objects.validator(validate)
    if type(id) == int:
        return redirect(reverse('books:book', kwargs={'id': id}))
    else:
        return redirect(reverse('books:add'))

def book(request, id):
    return redirect(reverse('books:index'))

Python/Django_Fundamentals/belt_reviewer/apps/review/templates/review/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Reviewer | Add Review</title>
  </head>
  <body>
    <form action="{% url 'books:new' %}" method="POST">
      {% csrf_token %}
      <h3>Book Title:<input type="text" name="title"/></h3>
      <h3>Author:</h3>
      <p>Choose from the list:
        <select name='author_select'>
            <option label=" "></option>
            <option value='add_my_own'>Added Below</option>
            {% for author in authors %}
            <option value='{{author.author}}'>{{author.author}}</option>
            {% endfor %}
        </select>
      </p>
      <p>
        Or add a new author: <input type="text" name="author_input"/>
      </p>
      <h3>Review:</h3>
      <textarea name="review" cols="50" rows="10" ></textarea>
      <h3>Rating
        <select name='rating' >
            <option label=" "></option>
            <option value='1'>1</option>
            <option value='1'>2</option>
            <option value='1'>3</option>
            <option value='1'>4</option>
            <option value='1'>5</option>
        </select>
        stars
      </h3>
      <input type="submit" value='Add Book and Review'>
    </form>
  </body>
</html>

Python/Django_Fundamentals/belt_reviewer/apps/review/templates/review/book.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Reviewer | Book</title>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>

Python/Django_Fundamentals/belt_reviewer/apps/review/templates/review/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Reviewer | Home</title>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>