Python/Django_Fundamentals/friends_list_assignment/Full_Friends/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.Make_Friends.urls', namespace='makefriends'))
]

Python/Django_Fundamentals/friends_list_assignment/apps/Make_Friends/urls.py
from django.conf.urls import url
# from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_person$', views.addPerson, name='add_person'),
    url(r'^create_friendship$', views.createFriendship, name='create_friendship')
]

Python/Django_Fundamentals/friends_list_assignment/enemy_list_assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.enemy_list.urls'))
]

Python/Django_Fundamentals/friends_list_assignment/apps/Make_Friends/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length = 45)

class Friendships(models.Model):
    friend1 = models.ForeignKey(Person)
    friend2 = models.ForeignKey(Person, related_name='friends')

Python/Django_Fundamentals/friends_list_assignment/apps/Make_Friends/views.py
from django.shortcuts import render, redirect
from .models import Person, Friendships
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    context = {
    'people': Person.objects.all(),
    'friendships': Friendships.objects.all()
    }
    return render(request, 'Make_Friends/index.html', context)

def addPerson(request):
    if request.method == "POST":
        Person.objects.create(name=request.POST['new_person'])
    return redirect(reverse('makefriends:index'))

def createFriendship(request):
    if request.method == "POST":
        Friendships.objects.create(friend1=Person.objects.get(id=request.POST['friend1']), friend2=Person.objects.get(id=request.POST['friend2']))
    return redirect(reverse('makefriends:index'))

Python/Django_Fundamentals/friends_list_assignment/apps/Make_Friends/templates/Make_Friends/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MARCO SUCKS</title>
    <style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;margin-top: 5px;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-9hbo{font-weight:bold;vertical-align:top}
.tg .tg-yw4l{vertical-align:top}
</style>
</head>
<body>
    <h1>Let's Make Some Enemies!</h1>

    <form action="{% url 'makefriends:add_person' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name='new_person'>
        <input type="submit" value='Add Person'>
    </form>

    <table class="tg">
      <tr>
        <th class="tg-9hbo">Enemies 1</th>
        <th class="tg-9hbo">Enemies 2</th>
      </tr>

    {% for friendship in friendships%}
      <tr>
        <td class="tg-yw4l">{{friendship.friend1.name}}</td>
        <td class="tg-yw4l">{{friendship.friend2.name}}</td>
      </tr>
      {% endfor %}
    </table>


    <form action="{% url 'makefriends:create_friendship' %}" method="post">
        {% csrf_token %}
        <p>Enemies 1: <select name='friend1'>
            {% for person in people %}
            <option value='{{person.id}}'>{{person.name}}</option>
            {% endfor %}
        </select>

        Enemies 2: <select name='friend2'>
            {% for person in people %}
            <option value='{{person.id}}'>{{person.name}}</option>
            {% endfor %}
        </select></p>

        <input type="submit" value='Create Enemies'>
    </form>
</body>

</html>